server {
    listen 80;
    server_name localhost;

    # PINDAHKAN KE SINI (Server Level)
    # Agar semua location tahu di mana folder utamanya
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Folder utama hasil build
    location / {
        # PENTING: Mengarahkan semua request ke index.html untuk SPA
        try_files $uri $uri/ /index.html;
    }

    # Optimasi Gzip
    gzip on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;
    gzip_vary on;

    # Caching untuk asset statis (Sudah otomatis pakai root dari atas)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
        
        # Tambahkan ini untuk memastikan file benar-benar dicari
        try_files $uri =404;
    }

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}